directory: ~/Music
library: ~/Data/musiclibrary.db
import:
  move: yes
  incremental_skip_later: yes
  bell: yes
ui:
  color: yes
musicbrainz:
  genres: yes
pluginpath:
  - /home/georg/git/beet-summarize/beetsplug
  - /home/georg/git/BeetsPluginYearFixer/beetsplug
  - /home/georg/git/BeetsPluginAutofix/beetsplug
  - /home/georg/git/BeetsPluginDescribe/beetsplug

plugins: fromfilename chroma acousticbrainz embedart fetchart replaygain scrub fish thumbnails fuzzy permissions lastgenre duplicates missing info summarize bpd autofix yearfixer describe

replaygain:
  backend: ffmpeg

thumbnails:
  dolphin: yes

